# Generated by Django 4.2.2 on 2023-07-27 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Agency",
        ),
    ]
