# Generated by Django 4.2.2 on 2023-07-27 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_user_agency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agency",
        ),
    ]
