# Generated by Django 4.2.2 on 2023-07-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0002_agency_agency_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="leaser",
        ),
        migrations.AddField(
            model_name="agency",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lmestate.property",
            ),
        ),
    ]
