# Generated by Django 4.2.2 on 2023-08-07 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0003_imagemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagemodel",
            old_name="file",
            new_name="image",
        ),
    ]
