# Generated by Django 4.2.2 on 2023-07-18 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lmestate", "0003_remove_property_leaser_agency_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="property",
        ),
        migrations.AddField(
            model_name="property",
            name="agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lmestate.agency",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
