# Generated by Django 4.2.2 on 2023-07-20 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0004_remove_agency_property_property_agency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
