# Generated by Django 4.2.2 on 2023-08-07 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0004_rename_file_imagemodel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="image_count",
        ),
    ]
