# Generated by Django 4.2.2 on 2023-07-20 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0005_property_property_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
