# Generated by Django 4.2.2 on 2023-07-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0007_image_alter_address_options_remove_property_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="img"),
        ),
    ]
