# Generated by Django 4.2.2 on 2023-07-22 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmestate", "0008_alter_image_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ImageModel",
        ),
    ]
